# Start Colab and the Google Drive environment

In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/

In [0]:
!ls "/content/drive/My Drive/"

 AchterhofMartin_u760301_Revision:Introduction_Individual_assignment.docx.gdoc
 Achterhof_RK.docx
 Achterhof_RK.docx.gdoc
'Answers Methodology exam prep.gdoc'
'Assignment 5 Law.gdoc'
'Assignment answers.gsheet'
'Characterizing the Real Estate Market Video.mp4'
'Colab Notebooks'
'Criteria Research paper.docx'
'Dates overview.pdf'
"Domains of Smart City's.gdoc"
 DSBG_14_abstract_RK.docx
 DSBG_14_abstract_RK.docx.gdoc
'DSBG_14_RK (1).docx'
'DSBG_14_RK (1).docx.gdoc'
'DSBG14_RK (1).docx.gdoc'
'DSBG_14_RK (2).docx.gdoc'
'DSBG14_RK (2).docx.gdoc'
 DSBG_14_RK.docx
 DSBG14_RK.docx
 DSBG_14_RK.docx.gdoc
 DSBG14_RK.docx.gdoc
 Eindcijfer.gsheet
'Feature description.gsheet'
'Hyperparameters .gsheet'
'Hyperparameters & silhouette score.gsheet'
'Introduction Resit.docx'
'JAAP dataset.gsheet'
'Keuzevakken + ects.gsheet'
 Law
'Law assignment 3.gdoc'
'Lieve Elisa, .gdoc'
'Master Data Science & Society'
'Masters Thesis Info Session.gdoc'
'Midterm Exam DM.gdoc'
'Practice exam notes.gdoc'
'Preference thesis topics.gsheet'
 Premaster
'Private law assignment.gdoc'
'Questions for external thesis partner .gdoc'
'Resit assignment.gdoc'
 Results.gsheet
'Samenwerken | Data science: Business & Governance'
'Statistics recap.gdoc'
'Test exam prep.gdoc'
 ThesisData
'Untitled document (1).gdoc'
'Untitled document (2).gdoc'
'Untitled document.gdoc'
'Untitled spreadsheet (1).gsheet'
'Untitled spreadsheet (2).gsheet'
'Untitled spreadsheet (3).gsheet'
'Untitled spreadsheet (4).gsheet'
'Untitled spreadsheet.gsheet'

In [0]:
!pip install -q keras

# Upload the Jaap.nl CSV file

In [0]:
!python3 "/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/part1_selectedfeatures/selected_features.csv"

  File "/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/part1_selectedfeatures/selected_features.csv", line 1
    ,ObjectId,CurrentPrice,Woonoppervlakte,Inhoud,Perceeloppervlakte,Kamers,Slaapkamers,Balkon,Garage,DaysOnline,ObjectType_Appartement,ObjectType_Herenhuis,ObjectType_Tussenwoning,ObjectType_Villa,ObjectType_Vrijstaande woning,ObjectType_Woonboerderij,Tuin_-,Tuin_Ja,City
    ^
SyntaxError: invalid syntax

In [0]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/part1_selectedfeatures/selected_features.csv", encoding = "ISO-8859-1")

In [0]:
df

       Postcode  ...  F52
0          1014  ...  NaN
1          1014  ...  NaN
2          1019  ...  NaN
3          1031  ...  NaN
4          1031  ...  NaN
...         ...  ...  ...
177025  9281 NS  ...  NaN
177026  9649 AC  ...  NaN
177027  9649 AZ  ...  NaN
177028  9649 KG  ...  NaN
177029  9756 AG  ...  NaN

[177030 rows x 52 columns]

# Installing packages

In [0]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import pyplot
from sklearn import preprocessing
import numpy as n
import matplotlib.pyplot as m
import pandas as p
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import feature_selection
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import silhouette_score
from yellowbrick.cluster import KElbowVisualizer
from sklearn.cluster import KMeans
from copy import deepcopy
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn import metrics
from sklearn.cluster import DBSCAN

# Creating different datasets city

In [0]:
df = df.drop(df.columns[0], axis=1)

In [0]:
#Weights
#weights = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5])

## Amsterdam --------------------------------------------

df_amsterdam = df['City'] == "Amsterdam"
df_amsterdam = df[df_amsterdam]
df_amsterdam = df_amsterdam.loc[:, df_amsterdam.columns != 'City']
df_amsterdam.to_csv("/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/df_cities/Amsterdam_excl_cluster.csv", encoding = "ISO-8859-1")

## Rotterdam --------------------------------------------

df_rotterdam = df['City'] == "Rotterdam"
df_rotterdam = df[df_rotterdam]
df_rotterdam = df_rotterdam.loc[:, df_rotterdam.columns != 'City']
df_rotterdam.to_csv("/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/df_cities/Rotterdam_excl_cluster.csv", encoding = "ISO-8859-1")

## Utrecht --------------------------------------------

df_utrecht = df['City'] == "Utrecht"
df_utrecht = df[df_utrecht]
df_utrecht = df_utrecht.loc[:, df_utrecht.columns != 'City']
df_utrecht.to_csv("/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/df_cities/Utrecht_excl_cluster.csv", encoding = "ISO-8859-1")

## Den Haag --------------------------------------------

df_denhaag = df['City'] == "'s-Gravenhage"
df_denhaag = df[df_denhaag]
df_denhaag = df_denhaag.loc[:, df_denhaag.columns != 'City']
df_denhaag.to_csv("/content/drive/My Drive/Master Data Science & Society/Year 2/Thesis/Data/df_cities/DenHaag_excl_cluster.csv", encoding = "ISO-8859-1")